export const descriptions = [
"<div><a href='https://www.museumwnf.org/'>MWNF Portal</a></div><div>A redesign for the homepage of Museum with No Frontiers. I was provided an initial outline from a UI designer but of course had to make changes along the way, and add some unaccounted for pages and sections. The site includes a sub-portal of sorts, accessible by clicking 'About' in the menu, and allows people to sign up for the MWNF newsletters.</div>",
"<div><a href='https://books.museumwnf.org/'>MWNF Books</a></div><div>A site dedicated to MWNF Books. The legacy site was outdated and convoluted, and now it matches other museums' book sites much more closely (including purchase links, and ability to see past versions, both physical and electronic). Also important to the director was the ability to switch languages for book information, which is part of the site where available.</div>",
"<div><a href='https://explore.museumwnf.org/'>Explore with MWNF</a></div><div>One of the most complicated sites I've had to build. A UI designer did most of the design work here, with not too much changing from what I was provided. However, functionality of the site includes displaying information at different levels, with many applicable filters, which was a bit of a logistical nightmare - but I think the end result looks and works nicely.</div>",
"<div><a href='https://islamicart.museumwnf.org/dynasties/'>DIA Dynasties</a></div><div>This is actually a sub-site of Discover Islamic Art (DIA), with the purpose of displaying and filtering date/history data. I was requested to modernize this portion of the site but match the design of the existing one. Unfortunately, I don't have a way to integrate my code with the original site, so it sort of stands on its own.</div>",
"<div><a href='https://glass.museumwnf.org/'>Discover MWNF Galleries</a></div><div>This was my first project upon signing up to volunteer for MWNF. They wanted to display the data they'd collected to create a 'Glass' online museum gallery. There was a partially completed existing site, Discover Carpet Art (DCA), that I was to match. After discussion and restructuring the API, I made Discover Glass Art (DGA) and then also revamped DCA. Then, later, I altered the code to make it a reusable and customizable template, and we launched all the Galleries they had information for, which you can see here (also a site I created): <a href='https://galleries.museumwnf.org/list'>MWNF Galleries</a></div>",
"<div><a href='https://codepen.io/evaplaysviolin/pen/vdvYxV'>Simon Says</a></div><div>A freeCodeCamp project, made in 2018. Project requirements include: up to 20 moves, color and tone for each button, an option for 'strict' mode which resets completely upon a mistake, and a display that shows how many moves are currently in the sequence.</div>",
"<div><a href='https://codepen.io/evaplaysviolin/pen/zRjMmG'>Tic Tac Toe</a></div><div>A freeCodeCamp project, made in 2018. Project requirements include: user can choose to be X or O, and plays against the computer. I believe there were no requirements for the computer's actions, so I randomized it.</div>",
"<div><a href='https://codepen.io/evaplaysviolin/pen/pabwBw'>Pomodoro Clock</a></div><div>A freeCodeCamp project, made in 2018. Project requirements include: 'pomodoro' timers (traditionally 25 minutes) broken up with 15-minute breaks, with a longer break suggested after four 'pomodoros', ability to restart, and allow the user to determine the length of timers. I added a pause button.</div>",
"<div><a href='https://codepen.io/evaplaysviolin/pen/ypMLyX'>JavaScript Calculator</a></div><div>A freeCodeCamp project, made in 2018. Project requirements include: ability to add, subtract, multiply, and/or divide, displaying the final amount when '=' is clicked, and a clear button. I elected to add resizing (for the numbers) and scrolling capability for when the numbers are too large/long for the 'screen'.</div>",
];
