export const descriptions = [
"<div><a href='https://exhibitions.museumwnf.org/the_use_of_colours_in_art/en/'>MWNF Exhibitions</a></div><div>A new template for Exhibitions (currently only one site is live, but more to come). The site is similar to the Discover MWNF Galleries but has a few additional sections breaking up the Exhibition into Themes and Subthemes. Each site can be assigned its own color scheme at the time of deployment.</div>",
"<div><a href='https://www.museumwnf.org/'>MWNF Portal</a></div><div>A redesign for the homepage of Museum with No Frontiers. I was provided a basic initial outline from a UI designer but had to make many changes. The site includes a sub-portal, accessible by clicking 'About' in the menu, and allows people to sign up for the MWNF newsletters.</div>",
"<div><a href='https://books.museumwnf.org/'>MWNF Books</a></div><div>A site dedicated to MWNF Books. The legacy site was very outdated, and now it matches other museums' book sites much more closely (including purchase links, and ability to see past versions, both physical and electronic). There are options to switch languages for book information where available.</div>",
"<div><a href='https://explore.museumwnf.org/'>Explore with MWNF</a></div><div>One of my most complicated projects and my first time working with a UI designer. Functionality of the site includes displaying information with many applicable filters, including images and maps (see a <a href='https://github.com/evaplaysviolin/sample'>sample</a>). Also my first time working with Google Custom Search.</div>",
"<div><a href='https://islamicart.museumwnf.org/dynasties/'>DIA Dynasties</a></div><div>A sub-site of Discover Islamic Art (DIA), with the purpose of displaying and filtering date/history data. I was requested to modernize this portion of the site but match the old design, so the UI is 1:1.</div>",
"<div><a href='https://glass.museumwnf.org/'>Discover MWNF Galleries</a></div><div>My first volunteer project for MWNF - to create an online museum gallery, with a recreation (from scratch) of the site design from a separate project. After discussion and a restructuring of the API, I made Discover Glass Art (DGA). Later, I altered the code to make it a reusable and customizable template, and we launched 35+ new Galleries, which you can see here (also a site I created): <a href='https://galleries.museumwnf.org/list'>MWNF Galleries</a></div>",
"<div><a href='https://codepen.io/evaplaysviolin/pen/vdvYxV'>Simon Says</a></div><div>A freeCodeCamp project, made in 2018. Project requirements include: up to 20 moves, color and tone for each button, an option for 'strict' mode which resets completely upon a mistake, and a display that shows how many moves are currently in the sequence.</div>",
// "<div><a href='https://codepen.io/evaplaysviolin/pen/zRjMmG'>Tic Tac Toe</a></div><div>A freeCodeCamp project, made in 2018. Project requirements include: user can choose to be X or O, and plays against the computer. There were no requirements for the computer's actions, so I randomized it.</div>",
"<div><a href='https://codepen.io/evaplaysviolin/pen/pabwBw'>Pomodoro Clock</a></div><div>A freeCodeCamp project, made in 2018. Project requirements include: 'pomodoro' timers (traditionally 25 minutes) broken up with 15-minute breaks, with a longer break suggested after four 'pomodoros', ability to restart, and allow the user to determine the length of timers. I added a pause button.</div>",
"<div><a href='https://codepen.io/evaplaysviolin/pen/ypMLyX'>JavaScript Calculator</a></div><div>A freeCodeCamp project, made in 2018. Project requirements include: ability to add, subtract, multiply, and/or divide, displaying the final amount when '=' is clicked, and a clear button. I added resizing for the numbers and scrolling capability for when the numbers are too large/long for the 'screen'.</div>",
];
